### ISSUE TITLE
How to make the voxel visualization?

### ISSUE THREAD

**Issue by doubleZ0108** [simicvm/snerg#1]
Really amazing work, I have a question about the visualization.
How do you make these voxel-shape scene visualization? I want to visualize the tensor data in my 3D research field (NOT Nerf), do you have any advice or guidance?
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/39005525/222947952-6f0b6c85-8883-4a23-bc73-a6b7bc03d1d4.png">

**Comment by simicvm** [comment]
Hey, sorry for a very late response. I am not the author of the original snerg work. It's best to consult the authors.
https://github.com/google-research/google-research/tree/master/snerg

**Comment by doubleZ0108** [comment]
Thanks whatever.

> 在 2023年4月15日，21:08，Marko Simic ***@***.***> 写道：﻿
> Hey, sorry for a very late response. I am not the author of the original snerg work. It's best to consult the authors.
https://github.com/google-research/google-research/tree/master/snerg
